jobs:
  try-minimize:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: actions/setup-node@v4
      with:
        node-version: 16
    - continue-on-error: true
      name: Install probe-image-size
      run: npm i probe-image-size@7.2.3 --ignore-scripts
    - continue-on-error: true
      name: Minimize simple images
      timeout-minutes: 3
      uses: actions/github-script@v7
      with:
        script: 'const script = require(''.github/workflows/image-minimizer.js'');

          await script({github, context});

          '
name: Image Minimizer
on:
  repository_dispatch:
    types: trigger-ga___image-minimizer.yml
permissions:
  issues: write
  pull-requests: write
