jobs:
  changed-lines-count-labeler:
    name: Automatically labelling pull requests based on the changed lines count
    permissions:
      pull-requests: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Set a label
      uses: TeamNewPipe/changed-lines-count-labeler@main
      with:
        configuration-path: .github/changed-lines-count-labeler.yml
        repo-token: ${{ secrets.GITHUB_TOKEN }}
name: PR size labeler
on:
  repository_dispatch:
    types: trigger-ga___pr-labeler.yml
permissions:
  contents: read
  pull-requests: write
